<a href="https://colab.research.google.com/github/vekoada/tensorflow-course/blob/main/00_tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Topics Covered
Introduction and TensorFlow version check

Creating Scalars, Vectors, and Matrices

Checking the number of dimensions

Creating tensors with different data types

Working with tensors using tf.Variable

Indexing and updating elements in tensors

Generating random tensors

Shuffling tensor elements

Creating tensors of ones and zeros

Converting NumPy arrays to tensors

Tensor shape, rank, axis, and size

Basic tensor indexing and slicing

Adding an extra dimension to tensors

Basic tensor operations (Addition, Multiplication)

Matrix multiplication and operations

Reshaping tensors and transposing

Dot product with tf.matmul and tf.tensordot

Changing data types with tf.cast

Aggregating tensors (min, max, mean, sum, variance, stdev)

Finding positional min and max values

Squeezing tensors to remove dimensions of size 1

One-hot encoding

Finding square root and logarithm

TensorFlow and NumPy compatibility



###Methods
`tf.constant()` - Creates tensors with specified values.

`tf.random.Generator.from_seed()` - Creates a random generator with a specific seed.

`random.normal()` - Generates random normal values using the given generator.

`tf.random.shuffle()` - Shuffles the order of elements in a tensor.

`tf.ones()` - Creates a tensor filled with ones.
`tf.zeros()` - Creates a tensor filled with zeros.

`np.arange()` - Generates an array of values with a specified range.

`tf.constant()` (with numpy array) - Converts a numpy array into a tensor.

`tf.reshape()` - Reshapes a tensor.

`tf.expand_dims()` - Adds extra dimensions to a tensor.

`tf.transpose(`) - Transposes a tensor.

`tf.tensordot()` - Computes the dot product of two tensors along specified axes.

`tf.matmul()` - Computes the matrix multiplication of two tensors.

tensor + scalar - Performs element-wise addition of a scalar to a tensor.

tensor * scalar - Performs element-wise multiplication of a tensor by a scalar.

`tf.cast()` - Changes the data type of a tensor.

`tf.reduce_min()`- Computes the minimum value in a tensor.

`tf.reduce_max()` - Computes the maximum value in a tensor.

`tf.reduce_mean()` - Computes the mean value of a tensor.

`tf.reduce_sum()` - Computes the sum of all elements in a tensor.

`tf.math.reduce_std()` - Computes the standard deviation of a tensor.

`tf.math.reduce_variance()` - Computes the variance of a tensor.

`tf.argmax()` - Finds the index of the maximum value in a tensor.

`tf.argmin()` - Finds the index of the minimum value in a tensor.

`tf.squeeze()` - Removes dimensions of size 1 from a tensor.

`tf.one_hot()` - Converts indices to one-hot encoded tensors.

`tf.range()` - Creates a tensor with a sequence of values within a specified range.

`tf.math.sqrt()` - Computes the square root of a tensor.

`tf.math.log()` - Computes the natural logarithm of a tensor.

`tf.config.list_physical_devices()` - Lists available physical devices.

`@` operator - Performs matrix multiplication.

`tf.random.set_seed()` - Sets the seed for random number generation.

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [ ]:
scalar = tf.constant(7) #create tensor
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#check number of dimensions
scalar.ndim

0

In [ ]:
#create vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#matrix
matrix = tf.constant([[12, 4], [14, 2]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12,  4],
       [14,  2]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#can alter dtype
another_matrix = tf.constant([[10., 3.], [4., 8.], [9., 4.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  3.],
       [ 4.,  8.],
       [ 9.,  4.]], dtype=float16)>

In [ ]:
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
#tensor with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
unchangeable_tensor, changeable_tensor


(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#changing one element in changeable tensor
#changeable_tensor[0] = 7
#changeable_tensor

In [ ]:
#nope. you have to use .assign
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
from tensorflow._api.v2 import random
#Creating 2 random tensors
random_1 = tf.random.Generator.from_seed(42) #setting seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
#shuffle order of elements in a tensor
not_shuffled = tf.constant([[10, 7], [2,11], [3,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2, 11],
       [10,  7],
       [ 3,  5]], dtype=int32)>

In [ ]:
#Create a tensor of all ones
tf.ones([10, 7])
#tf.zeros(shape=(3,4)) all zeros

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Turn NumPy arrays into tensors (tensors faster on GPUs)
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
#Can pass numpy arrays into tf.constant() to convert to tensor
A = tf.constant(numpy_A, shape=(2, 3, 4)) #shape must add up to same # of elements of original
B = tf.constant(numpy_A)
C = tf.constant(numpy_A, shape=(8,3))
A, B, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(8, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]], dtype=int32)>)

In [ ]:
#Shape, rank, axis/dimension, size
#Create a rank 4 tensor (ndim = 4)
r4_tensor = tf.zeros(shape=[2, 3, 4, 5])
r4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
r4_tensor.shape, r4_tensor.ndim, tf.size(r4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Getting various attributes of tensor
print("Datatype of every element:", r4_tensor.dtype)
print("Rank (no. dimensions):", r4_tensor.ndim)
print("Shape:", r4_tensor.shape)
print("Elements along 0 axis:", r4_tensor.shape[0])
print("Elements along last axis:", r4_tensor.shape[-1])
print("Total no. elements:", tf.size(r4_tensor).numpy()) #adding .numpy() simplifies output to only include size figure



Datatype of every element: <dtype: 'float32'>
Rank (no. dimensions): 4
Shape: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along last axis: 5
Total no. elements: 120


In [ ]:
#indexing: get first 2 elements of every dimension
first_2 = r4_tensor[:2, :2, :2, :2]
first_2

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#get first element from each dimension from each index except final dimension
r4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#creating rank 2 tensor
r2 = tf.zeros(shape=(2, 7))
r2

<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#get last item of each row
r2[:, -1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [ ]:
#add extra dimension (convert to rank 3) but keep information
r3 = r2[..., tf.newaxis] #... means for all the axes  (shorthand for :, :, etc)
r3

<tf.Tensor: shape=(2, 7, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]], dtype=float32)>

In [ ]:
#another way is with tf.expand_dims
tf.expand_dims(r2, axis=-1) # -1 expands final axis
# can also expand on other axes. numbers stay the same but shape changes

<tf.Tensor: shape=(2, 7, 1), dtype=float32, numpy=
array([[[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]],

       [[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]]], dtype=float32)>

In [ ]:
#operations:
# ADDITION
tensor = tf.constant([[10, 7], [5, 8]])
tensor + 10 #applies to every dimension

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [15, 18]], dtype=int32)>

In [ ]:
#MULTIPLICATION
# Same thing as subtraction, division
tensor * 20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [100, 160]], dtype=int32)>

In [ ]:
#also built-in functions
tf.multiply(tensor, 20) #tf function is faster on gpus at larger scale

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [100, 160]], dtype=int32)>

In [ ]:
#Matrix Multiplication (everything above is element-wise)
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[135, 126],
       [ 90,  99]], dtype=int32)>

In [ ]:
#Another example
A = tf.constant([[1, 2, 5],
                [7, 2, 1],
                [3, 3, 3]])
B = tf.constant([[3, 5],
                 [6, 7],
                 [1, 8]])
tf.linalg.matmul(A, B) #can ommit .linalg
# can use python '@' operator: A @ B

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#We can reshape matrixes
B_reshape = tf.reshape(B,shape=(2, 3))
B_reshape

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [ ]:
B_reshape = tf.reshape(B,shape=(1,6))
B_reshape

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[3, 5, 6, 7, 1, 8]], dtype=int32)>

In [ ]:
#TRANSPOSE changes rows in columns and vice-versa
#reshape shuffles values
tf.transpose(A), A

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 7, 3],
        [2, 2, 3],
        [5, 1, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>)

In [ ]:
#dot product with either tf.matmul or tf.tensordot
tf.tensordot(A,B, axes=1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
#changing dtype with tf.cast
B = tf.constant([[1.7, 8.8], [12.1, 3.4]])
print(B.dtype)
B = tf.cast(B, dtype=tf.float16)
B

<dtype: 'float32'>


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[ 1.7,  8.8],
       [12.1,  3.4]], dtype=float16)>

In [ ]:
#Aggregating tensors: finding summary vals (mean, max, etc)
#get abs values with tf.abs()
D = tf.random.Generator.from_seed(2).normal(shape=(10, 10))
D

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[-0.1012345 , -0.2744976 ,  1.4204658 ,  1.2609464 , -0.43640924,
        -1.9633987 , -0.06452483, -1.056841  ,  1.0019137 ,  0.6735137 ],
       [ 0.06987712, -1.4077919 ,  1.0278524 ,  0.27974114, -0.01347923,
         1.845181  ,  0.97061104, -1.0242516 , -0.6544423 , -0.29738766],
       [-1.3240396 ,  0.28785667, -0.8757901 , -0.08857018,  0.69211644,
         0.84215707, -0.06378496,  0.92800784, -0.6039789 , -0.1766927 ],
       [ 0.04221033,  0.29037967, -0.29604465, -0.21134205,  0.01063002,
         1.5165398 ,  0.27305737, -0.29925638, -0.3652325 ,  0.61883307],
       [-1.0130816 ,  0.28291714,  1.2132233 ,  0.46988967,  0.37944323,
        -0.6664026 ,  0.6054596 ,  0.19181173,  0.8045827 ,  0.4769051 ],
       [-0.7812124 , -0.996891  ,  0.33149973, -0.5445254 ,  1.5222508 ,
         0.59303206, -0.63509274,  0.3703566 , -1.0939722 , -0.4601445 ],
       [ 1.5420506 , -0.16822556, -0.4390865 , -0.4129243 ,  0.35877

In [ ]:
#find min
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=float32, numpy=-1.9633987>

In [ ]:
#max
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=float32, numpy=2.0261486>

In [ ]:
#mean
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0061117597>

In [ ]:
#sum
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=float32, numpy=0.61117595>

In [ ]:
#variance and STDEV
print(tf.math.reduce_std(D))
print(tf.math.reduce_variance(D))

tf.Tensor(0.84484875, shape=(), dtype=float32)
tf.Tensor(0.7137694, shape=(), dtype=float32)


In [ ]:
#Positional min and max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
max, min = tf.argmax(F), tf.argmin(F) #identifies the index that contains the max/min value
posmax = F[max] #identify value of max element given index
posmin = F[min]

#faster way to do this is with tf.reduce_max and tf.reduce_min

In [ ]:
#Squeezing tensors (removing dimensions of size 1)
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
print(G.shape)
G_squeezed = tf.squeeze(G)
print(G_squeezed.shape)

(1, 1, 1, 1, 50)
(50,)


In [ ]:
#One-hot encoding
list = [4, 3, 4, 5, 2, 3, 1, 4]
tf.one_hot(list, depth=5) #depth refers to no. of categories

<tf.Tensor: shape=(8, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Finding the square root
H = tf.cast(tf.range(1,10), dtype=tf.float32) #values 1 to 9 (cast to float for sqrt)
H_sq = tf.square(H)
tf.math.equal(tf.math.sqrt(H_sq), H)

<tf.Tensor: shape=(9,), dtype=bool, numpy=array([ True,  True,  True,  True,  True,  True,  True,  True,  True])>

In [ ]:
#Finding the log
tf.math.log(H) #also requires float

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
#TF and NumPy compatibility
# tensor directly from np array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#convert back to numpy array
type(np.array(J)) #this interoperability is useful for quickly accessing elements with []

numpy.ndarray

In [ ]:
#another way to get back to array
type(J.numpy())

numpy.ndarray

In [ ]:
#tensors directly from np arrays are dtype tf.float64
#tensors from lists are dtype tf.float32 - be aware of dtypes

In [ ]:
#check current access
tf.config.list_physical_devices()
#click 'change runtime type' to switch to GPU instead of CPU default
#tensorflow will automatically use cuda-enabled gpu whenever available

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [ ]:
#Practice:create scalar, vector, matrix, tensor
scalar = tf.constant(4)
vector = tf.constant([4, 2])
matrix = tf.constant([[2, 8],
                      [9, 3]])
tensor = tf.constant([[[[3, 6, 3], [2, 7, 7]],
                      [[8, 8, 1], [9, 0, 1]]],
                      [[[2, 1, 3], [6, 7, 5]],
                      [[4, 0, 0], [2, 1, 3]]]
                      ])
print(scalar)
print(vector)
print(matrix)
print(tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor([4 2], shape=(2,), dtype=int32)
tf.Tensor(
[[2 8]
 [9 3]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[[[3 6 3]
   [2 7 7]]

  [[8 8 1]
   [9 0 1]]]


 [[[2 1 3]
   [6 7 5]]

  [[4 0 0]
   [2 1 3]]]], shape=(2, 2, 2, 3), dtype=int32)


In [ ]:
# Find shape, rank, size of those tensors
print(scalar.shape,tf.size(scalar), scalar.ndim)
print(vector.shape, tf.size(vector), vector.ndim)
print(matrix.shape, tf.size(matrix), matrix.ndim)
print(tensor.shape, tf.size(tensor), tensor.ndim)

() tf.Tensor(1, shape=(), dtype=int32) 0
(2,) tf.Tensor(2, shape=(), dtype=int32) 1
(2, 2) tf.Tensor(4, shape=(), dtype=int32) 2
(2, 2, 2, 3) tf.Tensor(24, shape=(), dtype=int32) 4


In [ ]:
#Two tensors with random vals from 0 to 1 with shape [5, 300]
rand = tf.random.Generator
obj_1, obj_2 = random.uniform(shape=(5, 300)), random.uniform(shape=(5, 300))
obj_1, obj_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.95831835, 0.01680839, 0.3156035 , ..., 0.67105925, 0.76730955,
         0.20125735],
        [0.09921694, 0.02475083, 0.47242153, ..., 0.9631474 , 0.34333456,
         0.8129494 ],
        [0.08817983, 0.9311962 , 0.2293179 , ..., 0.41450226, 0.008304  ,
         0.02438807],
        [0.54814565, 0.37019622, 0.5272658 , ..., 0.8656951 , 0.19644582,
         0.5959221 ],
        [0.8964087 , 0.15288067, 0.3360591 , ..., 0.5725572 , 0.4094149 ,
         0.40059018]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.43555546, 0.52486527, 0.49674678, ..., 0.00552487, 0.3156761 ,
         0.22303641],
        [0.93881905, 0.02025807, 0.8929347 , ..., 0.47184265, 0.93879664,
         0.27382708],
        [0.8537835 , 0.287457  , 0.57827055, ..., 0.22605908, 0.62864304,
         0.28893173],
        [0.83130777, 0.13316286, 0.4270022 , ..., 0.96334374, 0.81353974,
         0.47423255],
        [0.20213

In [ ]:
# multiply those random tensors with matrix multiplication
print(tf.matmul(obj_1, tf.transpose(obj_2))) #had to transpose obj_2 to fit dimensions

tf.Tensor(
[[73.45298  74.09732  74.09219  73.014366 73.15687 ]
 [74.90097  75.270905 77.775635 74.378746 74.9059  ]
 [83.04033  79.46228  82.30002  80.63678  78.7219  ]
 [76.866684 76.41698  79.003265 77.38613  77.40253 ]
 [76.20903  74.70784  79.07423  75.5235   73.947845]], shape=(5, 5), dtype=float32)


In [ ]:
#find min and max vals of tensor with random vals b/t 0 and 1 with shape 224, 224, 3
obj_3 = tf.random.Generator
obj_3 = random.uniform(shape=(224, 224, 3))
print(tf.reduce_min(obj_3), '\n', tf.reduce_max(obj_3))

tf.Tensor(8.34465e-07, shape=(), dtype=float32) 
 tf.Tensor(0.9999887, shape=(), dtype=float32)


In [ ]:
#Squeeze a random tensor
obj_4 = tf.random.Generator
obj_4 = random.uniform(shape=(1, 224, 224, 3), minval=-1000, maxval=1000)
print(obj_4.shape, '\n', tf.squeeze(obj_4).shape)


(1, 224, 224, 3) 
 (224, 224, 3)


In [ ]:
#find index with max value in tensor with shape [10]
x = tf.random.Generator
x = random.uniform(shape=([10]))
posmax = tf.argmax(x)
print(x, '\n\n', posmax)

tf.Tensor(
[0.821141   0.5917634  0.90034425 0.28950942 0.07943332 0.25471914
 0.7148664  0.88859725 0.6240326  0.265391  ], shape=(10,), dtype=float32) 

 tf.Tensor(2, shape=(), dtype=int64)


In [ ]:
#one-hot encode that tensor
rounded_x = tf.cast(tf.math.round(x*10), dtype=tf.int32)
x_one_hot = tf.one_hot(rounded_x, depth=tf.size(rounded_x))
print(rounded_x)
print(x_one_hot)

tf.Tensor([8 6 9 3 1 3 7 9 6 3], shape=(10,), dtype=int32)
tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
